language:
  - "python"

python:
  - "3.3"

install:
  -  "pip install -r requirements.txt"

script:
  -  "nosetests"

services:
  -  "redis"
  
notifications:
  email:
    recipients:
      - papaloizouc@gmail.com
    on_success: change
    on_failure: always
